openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for weather
paths:
    /{city}:
        get:
            tags:
                - weather
            summary: show weather
            operationId: weather#show
            parameters:
                - name: city
                  in: path
                  description: Name of the city
                  required: true
                  schema:
                    type: string
                    description: Name of the city
                    example: Numquam aperiam possimus architecto molestiae ea.
                  example: Ab rem qui et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Weather'
                            example:
                                humidity: 0.453886238807127
                                temp: 0.8360313906939151
                                wind_speed: 0.6803703226679061
components:
    schemas:
        Weather:
            type: object
            properties:
                humidity:
                    type: number
                    description: Humidity in percent
                    example: 0.531713694171099
                    format: double
                temp:
                    type: number
                    description: Temperature in Celsius
                    example: 0.6338667163259205
                    format: double
                wind_speed:
                    type: number
                    description: Wind speed in meters per second
                    example: 0.22176372445959858
                    format: double
            example:
                humidity: 0.2328000032432123
                temp: 0.4685530891928919
                wind_speed: 0.2611685897949558
            required:
                - temp
                - wind_speed
                - humidity
tags:
    - name: weather
      description: The weather service returns current weather data for a given city.
